### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by davidmayr** [JasonTheKitten/Webicity-Lua-OLD#2]
How can I install it? And what is the current progress?

**Comment by JasonTheKitten** [comment]
I will be with you shortly

**Comment by JasonTheKitten** [comment]
Sorry, will try to get to it tomorrow. I had started typing some stuff up.

**Comment by JasonTheKitten** [comment]
Far from done. I've been busy writing a Discord bot.
Currently, as it is in early alpha, there is no installer. You will have to download it from GitHub or clone it with Git.
If you want to use the OC-compatible version, you will also have to clone (Ribbon)[https://github.com/JasonTheKitten/Ribbon], a much-closer-to-finished GUI framework I am writing
I think the version of Webicity on GitHub actually relies on an outdated version of Ribbon, so I will have to check that out.

Note that in both versions, the URL is currently hard-coded, as the navigation UI has not been written. The old version supported clicking (links)[https://example.com/] to go to other sites, however, most links did not work properly

The old attempt, which only worked on CC, could render links and text from HTML (and was horrendous).
![image](https://user-images.githubusercontent.com/15697938/79622237-77430080-80e4-11ea-88d6-72b34839c935.png)

The new attempt, which works on both CC and OC, can only render text files so far.
![image](https://user-images.githubusercontent.com/15697938/79668687-9b561e80-8184-11ea-9690-568ac9b2de1b.png)

If you are interested in progress on the new version
I had the new tokenizer for the HTML5 parser virtually finished, but I need to construct an ecma-style object system that I can map Web IDL to before I can construct and render the HTML tree.

I think I'll take a break from my bot to work on this some more.
